import Head from 'next/head'
import Profile from './Profile';

export default function Header() {
	return (
		<>
			<Head>
				<title>Electric Bike Rental System</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/bike.png" />
				<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet" />
			</Head>
			<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
				<div class="container">
					<a class="navbar-brand" href="/">Bike<span> Rental</span></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
						<span class="oi oi-menu"></span> Menu
					</button>

					<div class="collapse navbar-collapse" id="ftco-nav">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item"><a href="/" class="nav-link">Home</a></li>
							<li class="nav-item"><a href="/pricing" class="nav-link">Pricing</a></li>
							<li class="nav-item"><a href="/bikes" class="nav-link">Bikes</a></li>
							<li class="nav-item"><a href="/about" class="nav-link">About</a></li>
							<li class="nav-item"><a href="/dashboard" class="nav-link">Dashboard</a></li>
							<li class="nav-item"><a href="/api/auth/login" class="nav-link">Login</a></li>
							<li class="nav-item"><a href="/api/auth/logout" class="nav-link"><Profile /></a></li>
						</ul>
					</div>
				</div>
			</nav>
		</>
	);
}