import Head from 'next/head'
import Profile from './Profile';
import Link from 'next/link';
import { useUser } from '@auth0/nextjs-auth0/client';


export default function Header() {
	const { user } = useUser();

	return (
		<>
			<Head>
				<title>Electric Bike Rental System</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/bike.png" />
				<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet" />
			</Head>
			<nav className="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
				<div className="container">
					<a className="navbar-brand" href="/">Bike<span> Rental</span></a>
					<button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
						<span className="oi oi-menu"></span> Menu
					</button>

					<div className="collapse navbar-collapse" id="ftco-nav">
						<ul className="navbar-nav ml-auto">
							<li className="nav-item"><a href="/" className="nav-link">Home</a></li>
							{
								user && <>
									<li className="nav-item"><a href="/pricing" className="nav-link">Pricing</a></li>
									<li className="nav-item"><a href="/bikes" passHref={true} className="nav-link">Bikes</a></li>
									<li className="nav-item"><a href="/dashboard" className="nav-link">Dashboard</a></li>
								</>

							}
							<li className="nav-item"><a href="/about" className="nav-link">About</a></li>
							<li className="nav-item"><a href="/api/auth/login" className="nav-link">Login</a></li>
							{user && <li className="nav-item"><a href="/api/auth/logout" className="nav-link"><Profile /></a></li>}
						</ul>
					</div>
				</div>
			</nav>
		</>
	);
}